# Site settings
title: PZZ Blog
SEOTitle: 一抱一个胖猪猪的博客 | PZZ Blog
header-img: img/post-bg-desk.jpg
email: 2449253114@qq.com
description: "每一次失败都会导致成功.每一个胜利背后都有许多尝试"
keyword: "PZZ, PZZ Blog, 一抱一个胖猪猪的博客, 胖胖, 胖猪猪, Android, 安卓, 软件, uniapp"
url: "https://2449253114.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/2449253114/2449253114.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Life-long learning"
sidebar-avatar: /img/avatar-ykb.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:     ykbjson
csdn_username:       ykb19891118
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: a2449253114

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 51304063d6a23acb18a1                            #生成的clientID
  clientSecret: 411cfa746fddcb5c4a39ac97abc2882e5f034d81    #生成的clientSecret
  repo: 2449253114 .github.io    #仓库名称
  owner: 2449253114    #github用户名
  admin: 2449253114 
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: 

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: 'auto'               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "CSDN",
        href: "http://blog.csdn.net/qq_27342239"
    },{
        title: "Android",
        href: "https://www.android.com/"
    }
]
